### ISSUE TITLE
CLI Does Not Accept Correct Date

### ISSUE THREAD

**Issue by JovenSoh** [AY2425S1-CS2103T-W12-2/tp#134]
Although the Date is in the correct format, it's still showing a parse error

<img width="599" alt="image" src="https://github.com/user-attachments/assets/41f56389-d8e5-4f8f-964b-3b27addd2506">

**Comment by tzuennn** [comment]
What was the full command you used to get this behaviour? Is it something like this? 
`/v new n/ John Doe p/ 91234567 em/ john@gmail.com d/ 2024-02-02 s/ 00:10 e/ 23:59`
Since we removed the time field for volunteers, it's possible that the parser hasn’t been updated accordingly. As a result, running the above command may produce this error? Good find :)

**Comment by Fluffykan** [comment]
Issue arises as parser no longer accepts time for volunteer. Closed
