### ISSUE TITLE
[PE-D][Tester C] Unable to add event that span over midnight

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W12-2/tp#220]
![image.png](https://raw.githubusercontent.com/bryanckh/ped/main/files/1f1926e9-7b24-4e0c-b7c5-846910e5ed72.png)

For example, when I try to add an event that goes from 2024-03-02 23:00 to 2024-03-03 01:00, the application does not let me do so. This can seriously affect events that have a duration that crosses 00:00.

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: bryanckh/ped#4

**Comment by tzuennn** [comment]
This was the intended outcome, but it was not explicitly stated. Since our current setup uses a single date instead of a date list, any event spanning overnight (e.g., from 11 PM on 2024-11-10 to 1 AM on 2024-11-11) requires users to create two events: one from 11 PM to midnight on 2024-11-10 and another from midnight to 1 AM on 2024-11-11. Thank you for your suggestion; we'll consider it for future implementation.

**Comment by tzuennn** [comment]
Hi, thanks for pointing this out. However, this was the intended outcome. The rationale is that a volunteer may not have their own phone number and might use someone else’s, such as a child using a parent’s phone number as a contact. At the same time, the parents might also be volunteers. This is why we allow users to add multiple volunteers with the same phone number.
